apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: polaris
    meta.helm.sh/release-namespace: polaris
  creationTimestamp: "2022-08-23T12:39:13Z"
  labels:
    app: polaris
    app.kubernetes.io/component: dashboard
    app.kubernetes.io/instance: polaris
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: polaris
    app.kubernetes.io/part-of: polaris
    app.kubernetes.io/version: 5.4.1
    helm.sh/chart: polaris-5.4.1
  name: polaris
  resourceVersion: "11244"
  uid: 67d7a8bd-58ce-4f74-b333-2598e49a561c
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: polaris
subjects:
- kind: ServiceAccount
  name: polaris
  namespace: polaris
